FORMAT: 1A
HOST: http://private-eccc1d-kklaravelapi.apiary-mock.com

# laravel-api

This is api blah blah blah...

## Gyg Api [/gyg/1]

### List Gyg Tour [GET]

+ Response 200 (application/json)

        [
            {
                "a1": "b1",
                "a2": [
                    {
                        "b2": "c2",
                        "b3": 1024
                    }, {
                        "b5": "c3",
                        "b6": 1024
                    }, {
                        "b7": "c4",
                        "b8": 512
                    }, {
                        "b9": "c5",
                        "b10": 256
                    }
                ]
            }
        ]

